spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
test:
  oss: ali
  sv: bjh*&*&**************sssssssss

management:
  endpoints:
    web:
      exposure:
        include: '*'

#management:
#  endpoint:
#    info:
#      enabled: true
#  endpoints:
#    enabled-by-default: false

swagger:
  enable: true